### ISSUE TITLE
Some overlap with thermosteam

### ISSUE THREAD

**Issue by yoelcortes** [adelq/thermochem#19]
Very interesting package you are developing here. This is really just a cordial invitation to check out thermosteam: https://thermosteam.readthedocs.io/en/latest/index.html
I think there is some overlap, so you may be interested in using it. Thanks!

**Comment by adelq** [comment]
Hi Yoel! Thanks for sharing, it looks really nice and there certainly is some overlap. I'm working on adding a "Related Projects" page to the documentation to highlight thermosteam and other useful thermochemistry libraries in Python

**Comment by adelq** [comment]
It's up: https://thermochem.readthedocs.io/en/latest/related.html

Thanks again!

**Comment by yoelcortes** [comment]
Awesome, much appreciated! Thanks for looking through it.
