### ISSUE TITLE
JANAF_index.txt

### ISSUE THREAD

**Issue by ayushsgupta** [adelq/thermochem#21]
Hi there, I'm interested in using the thermochem package to access JANAF data. Out of curiosity, how did you originally gather the data to generate `JANAF_index.txt`?

**Comment by ZGainsforth** [comment]
Hi Ayush, I contacted the maintainers of the JANAF database and they sent me the info.  https://janaf.nist.gov  I think they have made it available on their website now also: https://janaf.nist.gov/formula.html

I use the code fairly regularly to get at the JANAF data for my own work, so don't hesitate to ping me if you need sample code or help with something.

**Comment by ayushsgupta** [comment]
Great, thanks! I just need to access experimental enthalpies of formation for various binary compounds. I'm guessing I would enter the specified parameters into `Janafdb.getphasedata` to get a `JanafPhase` object on which I'd call `DeltaH()`?

**Comment by ZGainsforth** [comment]
That's correct.  Like this to get the value in kJ/mol at 500, 550 and 1800 K.

from thermochem.janaf import Janafdb
db = Janafdb()
p = db.getphasedata(formula='O2Ti', name='Rutile', phase='cr')
print(p.DeltaH([500, 550, 1800]))
[-943670.  -943229.5 -936679. ]

**Comment by ayushsgupta** [comment]
Thanks!
