### ISSUE TITLE
issue with loading specific components

### ISSUE THREAD

**Issue by Noxical** [adelq/thermochem#22]
Hi,
Thanks you for making thermochem I find it very useful. However I have issue with the following:
Somehow I am not able to get the phase data of for example "Fe-006" or "Fe-007", see code below:

from thermochem.janaf import Janafdb
from thermochem.burcat import Elementdb
db = Janafdb()

#works
Fe = db.getphasedata(filename='Fe-001',cache=False)

#doesn't work
Fe = db.getphasedata(filename='Fe-006',cache=False)

It gives the following error:
ParserError: Expected 8 fields in line 42, saw 9. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

Do you know how to solve it?

**Comment by ZGainsforth** [comment]
@adelq This is already fixed in 0.8.1 but it never got pushed to pypi.  Can we update?

@Noxical For now, you can make a new venv/conda environment, git clone this repository and then:

cd thermochem
pip install -e .

That will use the latest source code and you shouldn't have the error.

**Comment by adelq** [comment]
@ZGainsforth thanks for looking into this. I've made some fixes to the tests to get everything running again and pushed a new release 0.8.2 to GitHub and PyPI.

@Noxical let us know if updating your thermochem version, either by using the latest source from GitHub as @ZGainsforth suggested or the 0.8.2 release on PyPI resolves your problem.

To upgrade to the latest available release on PyPI:
```
pip install -U thermochem
```
