### ISSUE TITLE
NIST-JANAF: wrong unit for DeltaH

### ISSUE THREAD

**Issue by apommel** [adelq/thermochem#24]
In the documentation, it is written that the unit for the output of the method `DeltaH` for the JANAF database is supposed to be in kJ/mol.
However, when I use it, the output is in J/mol:
```
>>> db = Janafdb()
>>> steam = db.getphasedata(formula='H2O', phase='g')
>>> steam.DeltaH([0, 100, 200])
array([-238921., -240083., -240900.])
```
If you check [here](https://janaf.nist.gov/tables/H-064.html), you can see that there is a 1e3 factor with the table.

Another thing would be with naming: the method is called `DeltaH` and in the documentation it is commented as 'Enthalpy', however I believe this is misleading as those values would be standard enthalpies of formation.

**Comment by adelq** [comment]
Hi Aurélien, you are correct, at some point we decided to try to convert all units to joules (74cbc5d1139309a55ba4e2320a4c887257d7c7c3), but this was inconsistently applied and documented, so I've reverted that commit and made it all consistent, I'm putting together a pull request (#25) to make those changes. Unfortunately, this will be a breaking change for users of this package, so I will be incrementing the version to indicate this.

I agree that the documentation for DeltaH should be the standard enthalpy of formation and have corrected that as well.

**Comment by apommel** [comment]
Hi Adel,

Having all the units in joules would indeed be fine, as long as it would be properly documented (which was not the case) and that everything would be consistent (currently JANAF `hef` method returns H-H°(Tr) in kJ/mol).
In any case, thank you for your quick response.
